wip: landing page template
rhdevs/rh-superapp pull request #10
Opened 2023-02-09 15:30 UTC by joshualeejunyi

2023-02-12 15:42 UTC, marcus-ong-qy requested changes
overall lgtm! just a few comments :)

It would be cool if you could document your code as well (like we did previously for the rhapp)

2023-02-12 15:42 UTC, marcus-ong-qy commented on components/LandingItems.tsx
> +import styled from "styled-components"
```suggestion
import Image from "next/image"
import { ChangeEvent, createContext, useContext, useEffect, useState } from "react"
import styled from "styled-components"
import { dummyData, Event } from "@/texts/common/dummy"
```
rearrange import sequence in accordance to the [style guide](https://www.notion.so/heads-of-rhdevs/RHDevs-Frontend-Code-Style-Guide-b5f294c047f14f78b370031afb2c73c5)

2023-02-12 15:42 UTC, marcus-ong-qy commented on package-lock.json
> +{
shouldn't have a package-lock.json file at all. Do delete it and make sure you used `yarn` instead of node

2023-02-12 15:42 UTC, marcus-ong-qy commented on texts/common/dummy.ts
> +export const dummyData:Event[] = [valentinesFundraiser, animalTherapy];
```suggestion
export const dummyData:Event[] = [valentinesFundraiser, animalTherapy];

```
newline at end of file... ensure you have Prettier configured to save on format on your IDE ya

2023-03-12 09:23 UTC, joshualeejunyi commented on components/LandingItems.tsx
> +import styled from "styled-components"
my prettier sets the order though haha

2023-03-12 09:23 UTC, joshualeejunyi commented on package-lock.json
> +{
okays noted

2023-03-14 14:40 UTC, marcus-ong-qy approved these changes
lgtm! rmb to rectify based on the comments before committing ya

2023-03-14 14:40 UTC, marcus-ong-qy commented on components/LandingItems.tsx
> +    style={{ flexGrow: 1, maxWidth: 300 }}
Try to avoid inline styling, use `styled-components` instead!

2023-03-14 14:40 UTC, marcus-ong-qy commented on components/LandingItems.tsx
> +    height={300}
same, avoid inline styling

2023-03-14 14:40 UTC, marcus-ong-qy commented on next.config.js
> +  },
Can check what is this for, and do we need to remove it in the future if we are not using it anymore?

2023-03-20 16:13 UTC, merged